class ReceiptNotExistsError(Exception):
    pass


class ReceiptAlreadyClosedError(Exception):
    pass
